/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package encryptedchat;

public class App {

    public static void main(String[] args) {
        ChatServer cs = new ChatServer();
        cs.start();
    }
}
